# Generated by Django 5.1.2 on 2024-10-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_app", "0002_alter_posts_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Posts",
        ),
    ]
